### PR TITLE
fix(preset-mini): `question-mark` rule should use `userConfig.envMode`

### LINKED ISSUE #258: UnoCSS Renders `?` Key CSS When Using Ternary
I'm using UnoCSS with Vue 3 Script Setup Sugar but even though I'm not using `?` key, UnoCSS and UnoCSS VSCode plugin detects ternary's question mark as a key and renders it. The presets I use are `presetUno` and `presetIcons`. I don't use `attributify` mode.
## My Code (<script setup>)
image
## Built CSS (formatted)
image

### PR DESCRIPTION
**Pull request by userquin**
closes #258

### CODE REVIEW

**Comment by antfu** [comment]
Not so sure. I expect reload only happens on dev?

**Comment by userquin** [comment]
> Not so sure. I expect reload only happens on dev?

I just build the `vite-svelte` and the `?` is there, on hmr is not necessary, but it seems the line I modified is being called on `build`.

**Comment by userquin** [comment]
it is being called here:
```ts
  async function getConfig() {
    await ready
    return rawConfig
  }
```

the `await ready` statement is just `const ready = reloadConfig()`

**Comment by userquin** [comment]
@antfu called here https://github.com/antfu/unocss/blob/main/packages/vite/src/modes/global/build.ts#L52?

**Comment by userquin** [comment]
@antfu maybe we can access the `userConfig` on the rule, changing it...

**Pull request merged**
