### PR TITLE
fix(preset-uno): remove extra spaces on grid rules

### LINKED ISSUE #134: `grid` stuff: remove extra spaces on rules

### PR DESCRIPTION
**Pull request by userquin**
closes #134

### CODE REVIEW

**Comment by hannoeru** [comment]
@userquin I think you need to rebuild cli package then update snapshot again to pass the test.

**Comment by userquin** [comment]
> @userquin I think you need to rebuild cli package then update snapshot again to pass the test.

Yeah, I'm building it rn...

**Comment by userquin** [comment]
@hannoeru can you checkout the branch and update it? I'm getting this error on windows (why `pnpm` is picking wrong `nvm`):

```bash
C:\Users\userquin>pnpm --version
6.22.2

C:\Users\userquin>node --version
v16.12.0

C:\Users\userquin>nvm list

  * 16.12.0 (Currently using 64-bit executable)
    16.7.0
    15.11.0
    15.5.1
    14.17.6
    12.18.3
    10.16.0
    8.17.0
    8.11.3
    6.12.0
    4.2.4
```

```bash
F:\work\projects\quini\GitHub\antfu\unocss-master>nr build

> @unocss/monorepo@0.11.2 build F:\work\projects\quini\GitHub\antfu\unocss-master
> pnpm -r --filter !playground --filter !fixtures run build && pnpm -r run build-post

node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'C:\Users\userquin\AppData\Roaming\Users\userquin\AppData\Roaming\nvm\v15.11.0\pnpm-global\5\node_modules\pnpm\bin\pnpm.cjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by johannschopplich** [comment]
Something seems off with the test results. The CLI tests output `max-width:7xl;` – could be a regression from a last feature, what do you think?

**Comment by userquin** [comment]
it is picking wrong path, it is concatenating twice the location (`Users\userquin\AppData\Roaming` is twice in the path):

`C:\Users\userquin\AppData\Roaming\Users\userquin\AppData\Roaming\nvm\v15.11.0\pnpm-global\5\node_modules\pnpm\bin\pnpm.cjs`

**Comment by userquin** [comment]
I'm checking the configuration...

**Comment by johannschopplich** [comment]
@userquin For Windows, you may want to use [fnm](https://github.com/Schniz/fnm) – a fast and simple Node.js version manager, built in Rust. 🙂

**Comment by userquin** [comment]
ok, latest pnpm  distros have not the same behavior when running install or runinng some script, it seems `~%dp0` returns wrong path when running scripts.

I just change the `pnpm.CMD` and `pnpx.CMD` on `nvm` to point to the right directory for `npm` dependencies.

**Pull request merged**
