### PR TITLE
feat(preset-uno): theme colors align with tw v3

### LINKED ISSUE #136: colors: current colors  from tw 2.1 to tw 3.0

### PR DESCRIPTION
**Pull request by chris-zhu**
closes #136

### CODE REVIEW

**Comment by chris-zhu** [comment]
Sorry, i can't pass `cli.test.ts`. Can you tell  me how to resolve the test ?

**Comment by chris-zhu** [comment]
Sorry, i can't pass `cli.test.ts`. Can you tell  me how to resolve the test ?

**Comment by hannoeru** [comment]
@chris-zhu Can you run `pnpm test:update` to update snapshots then commit changes?

**Comment by userquin** [comment]
@hannoeru I have main up to date, I also run `pnpm run test:update && pnpm run test`and passing all tests:
```bash
Test Suites: 14 passed, 14 total
Tests:       24 passed, 24 total
Snapshots:   18 passed, 18 total
Time:        15.212 s
Ran all test suites.
```

**Comment by chris-zhu** [comment]
@hannoeru   i update snapshots, but it still failed. i don't know how to resolve it

**Comment by chris-zhu** [comment]
> @chris-zhu Can you run `pnpm build && pnpm test:update` to update snapshots then commit changes?

thanks, finally done.

**Comment by antfu** [comment]
Hold for next minor version

**Comment by userquin** [comment]
@chris-zhu since this PR is hold to next minor, can you remove from this PR the position sticky and static? would be included on #153

**Comment by chris-zhu** [comment]
> @chris-zhu since this PR is hold to next minor, can you remove from this PR the position sticky and static? would be included on #153

ok.

**Pull request merged**
