### PR TITLE
feat: inspector

### PR DESCRIPTION
**Pull request by antfu**
This PR introduced a new package `@unocss/inspector` which will be shipped with `@unocss/vite`. It enables the ability to inspect the detection status similar to https://github.com/windicss/windicss-analysis and https://github.com/antfu/vite-plugin-inspect. Aim to solve #71 and others.

In userland, it will be accessible via `http://localhost:3000/__unocss/inspect` in apps that have UnoCSS installed.

image

To preview it locally, you can:

```bash
pnpm i
pnpm dev
```

```bash
# in another shell
cd packages/inspector
pnpm play
```

It's working in progress, contributions are greatly welcome (you can send PR to the `feat/inspector` branch)

/cc @hannoeru @edwardnyc @userquin in case you are interested

### CODE REVIEW

**Comment by edwardnyc** [comment]
Make a note. I'm trying to add the function of uploading and parsing files. I'm a little busy today. Try to bring up a PR after work

**Comment by antfu** [comment]
I am merging this. I have left a quick todo list here https://github.com/antfu/unocss/tree/main/packages/inspector#todo and feel free to pick any :) Thanks

**Comment by hannoeru** [comment]
Build error is because build processed in parallel, vite package build require inspector, but inspector's build process is still running, so there is no dts file in inspector's dist folder.

Just clan up the dist folder in local can reprod this issue.

**Comment by antfu** [comment]
> @antfu Build error is because build processes running in parallel, vite package build require inspector, but inspector's build process is still running, so there is no dts file in inspector's dist folder.
> 
> Just clean up the dist folder in local can reprod this issue.

Yeah, it's kinda tricky to solve (I tried to move `--parallel` it won't work either). While it's not affecting the userland anyway, I will leave it for later

**Pull request merged**
