### PR TITLE
feat(playground): execute scripts

### PR DESCRIPTION
**Pull request by sibbng**

### CODE REVIEW

**Comment by antfu** [comment]
What's the use case of this?

**Comment by sibbng** [comment]
> What's the use case of this?

I was trying to use Alpine.js to prototype some interactive components.

**Comment by antfu** [comment]
Can you share a playground link of your code? Thanks

**Comment by sibbng** [comment]
> Can you share a playground link of your code? Thanks

Here it is working demo from deploy preview: https://deploy-preview-98--ecstatic-mestorf-2e8afd.netlify.app/?html=DwZwxgTglgDgLgAhBMBeARAekwVwHYwDWA5gHRgD2AtpgIYA2MUeApgFYjoIAmLAZiwgA%2BYJnDR4QgFAIpwblABuCAB4BabrTi0MAbwQUYLPAC4EfBiBYIAvumkJHCYACMccOBTwIAAmHpQYIQYhsYIqAgAhKF49gDCAUEInggsKjC0eNyibh5eDjJOoBne6iAAFhQA7iFGsQ5OjnFecMZwpB2FjqIgJdKiCopCQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA

**Comment by sibbng** [comment]
I did some research and came to the conclusion that this approach would be unsafe. I came up with some solutions but they have their own drawbacks or requires a too much change around. I don't think it's worth it for now.

**Pull request closed without merging**
