### PR TITLE
feat(preset-wind): add `tailwind` missing animations

### LINKED ISSUE #241: animate-pulse is scaling the object
The pulse keyframes are wrong and do not align with windicss or tailwind.
Instead of pulsing opacity it pulses scale.

### PR DESCRIPTION
**Pull request by userquin**
Added missing tailwind `pulse` and `bounce`, `tw-pulse` and `tw-bounce` respectively, `spin` and `ping` was already there.

closes #241

### CODE REVIEW

**Comment by antfu** [comment]
Maybe we should align the unprefixed one with Tailwind and have the one from animated.css as something like `pulse-alt`?

**Comment by userquin** [comment]
ok

**Comment by userquin** [comment]
updated also playground to use `animate-bounce-alt`

**Comment by userquin** [comment]
@chris-zhu can you take a look to the changes I've made?

**Pull request merged**
